pipeline {
  agent any

  options {
    timestamps()
    disableConcurrentBuilds()
    buildDiscarder(logRotator(numToKeepStr: '20'))
  }

  environment {
    // Region can be changed as needed
    AWS_REGION = 'us-east-2'

    // Where reports are written by your project
    REPORTS_DIR = 'reports'

    // Dashboard endpoint (set to your server if used)
    // Example: http://<dashboard-host>:5000/api/ingest
    DASHBOARD_URL = ''
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
        sh 'git rev-parse --short HEAD'
      }
    }

    stage('Setup Python deps') {
      steps {
        sh '''
          set -e
          python3 -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install jinja2 weasyprint requests pyyaml
        '''
      }
    }

    stage('Workspace Sanity Check') {
      steps {
        sh '''
          set -e
          echo "=== Workspace ==="
          pwd
          ls -la

          echo "=== utils directory ==="
          ls -la utils || true

          echo "=== Find build_findings ==="
          find . -maxdepth 4 -type f -iname "*build_findings*" -print || true

          echo "=== main.py present? ==="
          test -f main.py && echo "main.py OK" || (echo "ERROR: main.py missing" && exit 1)
        '''
      }
    }

    stage('Run Scanner (non-fatal)') {
      steps {
        catchError(buildResult: 'SUCCESS', stageResult: 'SUCCESS') {
          // If you have AWS credentials in Jenkins, bind them here (recommended).
          // If not, leave it as-is and AWS scan may fail but host scan can still proceed.
          // Replace 'aws-creds' with your Jenkins credential ID if you create one.
          withCredentials([
            // Comment these two lines out if you are not using AWS creds in Jenkins:
            // usernamePassword(credentialsId: 'aws-creds', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY')
          ]) {
            sh '''
              set +e
              . .venv/bin/activate

              # If you rely on AWS_PROFILE, set it here; otherwise keep blank and rely on env credentials.
              export AWS_PROFILE=${AWS_PROFILE:-}
              export AWS_REGION=${AWS_REGION}

              python3 main.py
              rc=$?
              echo "[i] main.py exit code: ${rc} (non-fatal stage)"
              exit 0
            '''
          }
        }
      }
    }

    stage('Build Findings') {
      steps {
        sh '''
          set -e
          . .venv/bin/activate

          mkdir -p "${REPORTS_DIR}"

          echo "=== Pre-check reports directory ==="
          ls -la "${REPORTS_DIR}" || true

          echo "=== Ensure combined_summary.json exists ==="
          if [ ! -f "${REPORTS_DIR}/combined_summary.json" ]; then
            echo "ERROR: ${REPORTS_DIR}/combined_summary.json not found."
            echo "This file should be generated by main.py. Check scanner output above."
            exit 1
          fi

          echo "=== Ensure findings builder exists ==="
          if [ ! -f "utils/build_findings.py" ]; then
            echo "ERROR: utils/build_findings.py not found in workspace."
            echo "Run: ls -la utils && ensure the file is committed/pushed to GitHub."
            exit 1
          fi

          echo "=== Build findings (run by path, not module) ==="
          python3 utils/build_findings.py

          echo "=== Post-check reports directory ==="
          ls -la "${REPORTS_DIR}"
        '''
      }
    }

    stage('Risk Report') {
      steps {
        sh '''
          set -e
          . .venv/bin/activate

          # Adjust to your actual report generator command/script
          # Example: python3 utils/risk_report.py
          if [ -f "utils/risk_report.py" ]; then
            python3 utils/risk_report.py
          else
            echo "WARNING: utils/risk_report.py not found; skipping risk report generation."
          fi

          ls -la "${REPORTS_DIR}" || true
        '''
      }
    }

    stage('Publish Report') {
      steps {
        sh '''
          set -e
          echo "Archiving reports as Jenkins artifacts (also done in post)."
        '''
      }
    }

    stage('Push to Dashboard (non-fatal)') {
      steps {
        catchError(buildResult: 'SUCCESS', stageResult: 'SUCCESS') {
          sh '''
            set +e
            . .venv/bin/activate

            if [ -z "${DASHBOARD_URL}" ]; then
              echo "INFO: DASHBOARD_URL not set; skipping dashboard push."
              exit 0
            fi

            # Example push (adjust to your API + payload expectations)
            # If you have a script: python3 utils/push_to_dashboard.py --url "$DASHBOARD_URL"
            if [ -f "utils/push_to_dashboard.py" ]; then
              python3 utils/push_to_dashboard.py --url "${DASHBOARD_URL}"
            else
              echo "WARNING: utils/push_to_dashboard.py not found; skipping."
            fi

            exit 0
          '''
        }
      }
    }
  }

  post {
    always {
      echo 'Pipeline completed.'

      // Always archive reports so you can download them from Jenkins even if a later stage fails
      archiveArtifacts artifacts: 'reports/**', allowEmptyArchive: true

      // If you generate HTML reports, this publishes them in Jenkins (optional)
      // publishHTML(target: [
      //   allowMissing: true,
      //   alwaysLinkToLastBuild: true,
      //   keepAll: true,
      //   reportDir: 'reports',
      //   reportFiles: 'report.html',
      //   reportName: 'Cloud & Host Misconfiguration Report'
      // ])
    }
  }
}
